name: padelmatch
description: "Un proyecto que permite emparejar jugadores de pádel y gestionar partidos."
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.5.0

  # Navegación
  go_router: ^14.0.1

  # State management
  flutter_riverpod: ^2.5.1

  # Localización
  flutter_localizations:
    sdk: flutter
  intl: 0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter/Inter-VariableFont_opsz,wght.ttf